// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdZm9Z2ILx2Cj8NKOvX0poQsyEqvV5od4',
    appId: '1:84074855927:web:9bc3300393fe9ca160c2f2',
    messagingSenderId: '84074855927',
    projectId: 'firstapp-2341c',
    authDomain: 'firstapp-2341c.firebaseapp.com',
    storageBucket: 'firstapp-2341c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzd2yt1VWkYDRrJ3caz3DHYl0nZ7UlbFw',
    appId: '1:84074855927:android:97160951d1817a4960c2f2',
    messagingSenderId: '84074855927',
    projectId: 'firstapp-2341c',
    storageBucket: 'firstapp-2341c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr7NxJjAnAyX0LFmh3_QtXCNZWJT9xZXA',
    appId: '1:84074855927:ios:b3b8dad23e804b9960c2f2',
    messagingSenderId: '84074855927',
    projectId: 'firstapp-2341c',
    storageBucket: 'firstapp-2341c.appspot.com',
    iosClientId: '84074855927-pt42a0o9eig87p57d12klfr1n0a88pdc.apps.googleusercontent.com',
    iosBundleId: 'com.mjk.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr7NxJjAnAyX0LFmh3_QtXCNZWJT9xZXA',
    appId: '1:84074855927:ios:f91b857e0d03c3c160c2f2',
    messagingSenderId: '84074855927',
    projectId: 'firstapp-2341c',
    storageBucket: 'firstapp-2341c.appspot.com',
    iosClientId: '84074855927-1g97549t8f2j7aapq1cq5lin0abne99f.apps.googleusercontent.com',
    iosBundleId: 'com.mjk.firstapp.RunnerTests',
  );
}
